name: Test dependencies for security issues with Snyk

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  dependencies-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['2.x', '3.x']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

    - name: Show environment
      run: |
        python --version
        pip --version
        poetry --version

    - uses: snyk/actions/setup@master

    - name: Install Python dependencies with Poetry
      run: poetry install -v

    - name: Run tests
      run: poetry run pytest

    - name: Test dependencies with Snyk
      run: snyk test --json-file-output=snyk_report.json
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Monitor dependencies for security issues with Snyk
      run: snyk monitor
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Convert Snyk results to SARIF format
      run: |
        npm install -g snyk-to-sarif
        snyk-to-sarif convert --input-file snyk_report.json --output-file snyk_report.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Upload Snyk results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk_report.sarif
