name: Snyk Open Source Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Snyk
      uses: snyk/actions/setup@master

    - name: Run Snyk to check for vulnerabilities
      run: |
        export exitcode=0
        snyk test --json-file-output=snyk_report.json || export exitcode=$?
        if [$exitcode -eq 1]; then
            echo "[*] Found issues"
            exit 0
        fi

      #  snyk test --json-file-output=snyk_report.json
            env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Monitor dependencies for security issues with Snyk
      run: snyk monitor
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Create String Output
      id: Snykstr
      run: |
        SNYK_OUTPUT=$(snyk test --json-file-output=snyk_report.json)
        delimiter="$(openssl rand -hex 8)"
        echo "PLAN<<${delimiter}" >> $GITHUB_OUTPUT
        echo "$SNYK_OUTPUT" >> $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT

   
    - name: Publish Snyk Report
      env:
        SNYK_OUT: ${{ steps.Snykstr.outputs.PLAN }}
      run: |
        echo "## Snyk output" >> $GITHUB_STEP_SUMMARY
        echo "<details><summary>Click to view details</summary>" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo '```terraform' >> $GITHUB_STEP_SUMMARY
        echo "$SNYK_OUT" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY
       

    # - name: Convert Snyk results to SARIF format
    #   run: |
    #     npm install -g snyk-to-sarif
    #     snyk-to-sarif convert --input-file snyk_report.json --output-file snyk_report.sarif

    # - name: Upload Snyk results to GitHub Code Scanning
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: snyk_report.sarif
