name: OWASP ZAP Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: ZAP Scan
        id: zap
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://pygoat2.azurewebsites.net/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -J zap_report.json -r zap_report.html -w zap_report.md'
        env:
          GITHUB_TOKEN: ${{ secrets.ZAP_TOKEN }}
        continue-on-error: true # Ensure subsequent steps run even if this step fails

      - name: Upload ZAP JSON Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: zap-report-json
          path: zap_report.json

      - name: Upload ZAP HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: zap-report-html
          path: zap_report.html

      - name: Check ZAP Logs
        if: always()
        run: cat /github/workspace/zap.out || echo "No ZAP logs found"

      - name: Upload ZAP Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: zap-log
          path: /github/workspace/zap.out
