name: DAST Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    name: Run ZAP Scan with Nightly Image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull ZAP Nightly Image
        run: docker pull ghcr.io/zaproxy/zaproxy:nightly

      - name: Run ZAP Scan
        run: |
          docker run --user root -v ${{ github.workspace }}:/zap/wrk/ \
          -t ghcr.io/zaproxy/zaproxy:nightly \
          bash -c "zap-full-scan.py -t http://pygoat2.azurewebsites.net/ -r zap_report2.html && chmod 777 /zap/wrk/zap_report.html"
          
      - name: Upload ZAP HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-html
          path: zap_report.html

